// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdSq5U3lfRl6sqN6x1V6IffAk2xj_Xa6M',
    appId: '1:924078749181:web:796a0e9398ddce24b09594',
    messagingSenderId: '924078749181',
    projectId: 'denem01-1fe53',
    authDomain: 'denem01-1fe53.firebaseapp.com',
    databaseURL: 'https://denem01-1fe53-default-rtdb.firebaseio.com',
    storageBucket: 'denem01-1fe53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo4NQyCeUeTInKQHN5w0w502SoMelELSA',
    appId: '1:924078749181:android:3c5b33666450fe1eb09594',
    messagingSenderId: '924078749181',
    projectId: 'denem01-1fe53',
    databaseURL: 'https://denem01-1fe53-default-rtdb.firebaseio.com',
    storageBucket: 'denem01-1fe53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXOJNZbjghdaJWpv7yjTdxgTIGJm3gNUA',
    appId: '1:924078749181:ios:ba8ba3682b45f57fb09594',
    messagingSenderId: '924078749181',
    projectId: 'denem01-1fe53',
    databaseURL: 'https://denem01-1fe53-default-rtdb.firebaseio.com',
    storageBucket: 'denem01-1fe53.appspot.com',
    iosBundleId: 'com.example.yasunApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXOJNZbjghdaJWpv7yjTdxgTIGJm3gNUA',
    appId: '1:924078749181:ios:ba8ba3682b45f57fb09594',
    messagingSenderId: '924078749181',
    projectId: 'denem01-1fe53',
    databaseURL: 'https://denem01-1fe53-default-rtdb.firebaseio.com',
    storageBucket: 'denem01-1fe53.appspot.com',
    iosBundleId: 'com.example.yasunApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdSq5U3lfRl6sqN6x1V6IffAk2xj_Xa6M',
    appId: '1:924078749181:web:b26fc055cf35d691b09594',
    messagingSenderId: '924078749181',
    projectId: 'denem01-1fe53',
    authDomain: 'denem01-1fe53.firebaseapp.com',
    databaseURL: 'https://denem01-1fe53-default-rtdb.firebaseio.com',
    storageBucket: 'denem01-1fe53.appspot.com',
  );
}
